# Generated by Django 3.0.8 on 2021-08-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCodeCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=400, verbose_name='Kupon Liste Adı')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Kupon Adet')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Ücret')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kupon Kod Oluştur',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CouponCodeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kupon Kodu')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Ücret')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktif')),
                ('coupon_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='checkout.CouponCodeCreate', verbose_name='Kupon Listesi')),
            ],
            options={
                'verbose_name': 'Kupon Kodları',
                'verbose_name_plural': 'Kupon Kodları Listesi',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
    ]
