# Generated by Django 3.2.4 on 2021-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='öğretmen adı')),
                ('surname', models.CharField(max_length=20, verbose_name='öğretmen soyadı')),
                ('type', models.CharField(choices=[('Öğretmen', 'öğretmen'), ('Müdür', 'müdür'), ('Öğrenci', 'öğrenci')], default='Müdür', max_length=10)),
            ],
        ),
    ]
