# Generated by Django 3.2.6 on 2021-08-04 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Şehir')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehir Liste',
                'ordering': ('name',),
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmailPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=256, verbose_name='Mail')),
            ],
            options={
                'verbose_name': 'E-Mail',
                'verbose_name_plural': 'E-Mail Liste',
                'ordering': ('text',),
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Adres İsmi')),
                ('first_name', models.CharField(max_length=256, verbose_name='Alıcı Ad')),
                ('last_name', models.CharField(max_length=256, verbose_name='Alıcı Soyad')),
                ('tc', models.BigIntegerField(blank=True, null=True, verbose_name='TC veya Vergi Numarası')),
                ('company_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Şirket Adı ( Kurumsal Faturalar İçin )')),
                ('company_tax', models.CharField(blank=True, max_length=256, null=True, verbose_name='Vergi Dairesi( Kurumsal Faturalar İçin )')),
                ('street_address_1', models.TextField(verbose_name='Adres')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Posta Kodu')),
                ('phone', models.CharField(blank=True, default='', max_length=128, verbose_name='Telefon')),
                ('billing_address', models.BooleanField(choices=[(True, 'Evet'), (False, 'Hayır')], default=True, null=True, verbose_name='Fatura Adresi')),
                ('shipping_address', models.BooleanField(choices=[(True, 'Evet'), (False, 'Hayır')], default=True, null=True, verbose_name='Teslimat Adresi')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.citylist', verbose_name='Şehir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres_user', to=settings.AUTH_USER_MODEL, verbose_name='Adres Sahibi')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'ordering': ('pk',),
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
    ]
